### ISSUE TITLE
README example uses non-existing method

### ISSUE THREAD

**Issue by nbigaouette-eai** [davidMcneil/mnist#1]
The README has:
```
    let Mnist { trn_img, trn_lbl, .. } = MnistBuilder::new()
         .image_format_28x28()
         .label_format_1x1()
[...]
```
but both `image_format_28x28()` and `label_format_1x1()` are invalid methods.

They should probably be removed from the example (as is the case in the documentation).

**Comment by davidMcneil** [comment]
Thanks! That example was from an outdated version.
