### ISSUE TITLE
Expected filename issue

### ISSUE THREAD

**Issue by nbigaouette-eai** [davidMcneil/mnist#2]
`MnistBuilder` expects the MNIST data to be, for example, `data/train-images.idx3-ubyte`. But the [Mnist web size](http://yann.lecun.com/exdb/mnist/) gives `train-images-idx3-ubyte.gz`; Note the `.idx3` vs `-idx3`.

This means that I have to rename the files after having downloaded the original ones, which can be confusing.

I guess `MnistBuilder` should expect files with `.idx3` and not `-idx3`?

**Comment by davidMcneil** [comment]
Thanks! My file manager simply decided to put the . there when it extracted the files. Using the filepath with all -s makes much more sense.
